import "@/assets/styles/index.css";
import { SensorProvider } from "@/context/useSensorContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SensorProvider>{children}</SensorProvider>
      </body>
    </html>
  );
}
