spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: missing_back
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
    hikari:
      connection-timeout: 15000
      maximum-pool-size: 10
      max-lifetime: 240000
      leak-detection-threshold: 10000
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
      jdbc:
        time-zone: Asia/Seoul
  servlet:
    multipart:
      max-file-size: 20MB # 파일당 최대 크기 설정
      max-request-size: 20MB # 전체 요청 크기 설정

logging:
  level:
    org:
      springframework: DEBUG

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY_ID}
      secret-key: ${S3_SECRET_ACCESS_KEY}
    region:
      static: us-east-1
    stack:
      auto: false

jwt:
  secret: ${JWT_SECRET}
  access-token-ms: ${JWT_ACCESS_TOKEN_MS}
  refresh-token-ms: ${JWT_REFRESH_TOKEN_MS}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
